"""
核心业务测试脚本

Totoro Campus Run - Official API Submission
Reads route.json and submits directly to app.xtotoro.com

Flow:
    1. Load route data from route.json (generated by route.py)
    2. Load credentials from session.json
    3. Call getRunBegin (notify server run started)
    4. Call sunRunExercises (submit summary: time, speed, distance, steps)
    5. Call sunRunExercisesDetail (submit GPS track)

All requests use RSA PKCS#1 encryption (public key) for sending.
Server responses are Base64 strings decrypted with RSA private key.

Usage:
    cd test
    python route.py --start-time "14:00:00"
    python submit_run.py --route-file route.json --config session.json
"""

import json
import sys
import hashlib
import base64
import argparse
from pathlib import Path

import requests
requests.packages.urllib3.disable_warnings()

# =============================================================================
# RSA Keys (extracted from totoro-paradise/src/data/rsaKeys.ts)
# =============================================================================

# Used to encrypt request payloads before sending to server
PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDU/j+c5FdkEwhSIF9jmw+050iN
0/yfjhk/669RyFiG5wu0Adpk3NR2Ikbo2lA+rTBJBx1bpGVGCvMKKQ/pljNUSmJt
JaM5ieONFrZD6RhSUbjrNENH89Ks9GGWi+1dkOfdSHNujQilF5oLOIHez1HYmwml
ADA29Ux4yb8e4+PtLQIDAQAB
-----END PUBLIC KEY-----"""

# Used to decrypt server responses (which are RSA-encrypted Base64 strings)
PRIVATE_KEY_PEM = """-----BEGIN PRIVATE KEY-----
MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBANT+P5zkV2QTCFIg
X2ObD7TnSI3T/J+OGT/rr1HIWIbnC7QB2mTc1HYiRujaUD6tMEkHHVukZUYK8wop
D+mWM1RKYm0lozmJ440WtkPpGFJRuOs0Q0fz0qz0YZaL7V2Q591Ic26NCKUXmgs4
gd7PUdibCaUAMDb1THjJvx7j4+0tAgMBAAECgYEAnqMvZf98R4EVdXW/FkTrkeWh
WGFHit8fV0iHL/Z0WSXExbGLpAwGAmbNQak4kzYS/JFcAGGVPHHzSuIChAvm9ciE
WlUst5BGc7kO3gJs67zS7+nIkOHhr+oFvHcxy6J4yg1HoOftqcAL4soyI7E6knoh
1zX+mcZNIrduZHD6IoECQQD2qwgD6kiiynr3jaqSE2TIuRlwrBD3Xuslbd1UMam0
BIeeDJWGHlGnkIvveZ2uMjG7dRta6GOEgrAESg5NPKx1AkEA3Q0TujLihvwu+Drg
SEGLU21iziPsms4Ush5268ImLEoK2HuKwj1JcWRhx1au1DnK48DWTT7ZLxblTI18
AF8G2QJBALx+rCxZv1HvSxKbhmoEOfMNR7yLMJfoR+cdUpIBNX6kK4KCeUy5JIrY
8aZ5mB5CqzBl6BaLGWlseNd+Q/mP0PUCQFmKeYo8IHyTXKdamg1K15gkwBhGfwo6
HjIEmyFm1LWuDHSinpON5dkT03O+zjTTcDcPnv9NTQaBHMMEsM0psQkCQQCZ9znK
9fLouRHaWb7HqR3nldeUYoA3NuL+69Q1FOBeoIy5zoU6UDkqxK+uoA2rnZa+5If4
d2cAmn4N+8uqjvjA
-----END PRIVATE KEY-----"""

BASE_URL = "https://app.xtotoro.com/app"


# =============================================================================
# RSA Cryptography Functions
# =============================================================================

def rsa_encrypt(data: str) -> str:
    """
    Encrypt plaintext JSON string using RSA public key (PKCS#1) with chunking.
    
    RSA keys have a maximum message size (key_length - 11 bytes for PKCS#1).
    For a 1024-bit key, this is 117 bytes. Longer messages must be split
    into chunks, encrypted separately, and concatenated.
    
    The server decrypts by splitting the ciphertext into key-length chunks
    and decrypting each one, then concatenating the plaintext.
    
    Args:
        data: Plaintext JSON string to encrypt
        
    Returns:
        Base64-encoded RSA ciphertext (may contain multiple encrypted chunks)
    """
    data_bytes = data.encode('utf-8')
    
    try:
        import rsa
        pub_key = rsa.PublicKey.load_pkcs1_openssl_pem(PUBLIC_KEY_PEM.encode())
        keylength = rsa.common.byte_size(pub_key.n)
        max_chunk = keylength - 11  # PKCS#1 v1.5 padding overhead
        
        encrypted_chunks = []
        for i in range(0, len(data_bytes), max_chunk):
            chunk = data_bytes[i:i + max_chunk]
            encrypted = rsa.encrypt(chunk, pub_key)
            encrypted_chunks.append(encrypted)
        
        return base64.b64encode(b''.join(encrypted_chunks)).decode('utf-8')
        
    except ImportError:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import padding
        pub_key = serialization.load_pem_public_key(PUBLIC_KEY_PEM.encode())
        encrypted = pub_key.encrypt(data_bytes, padding.PKCS1v15())
        return base64.b64encode(encrypted).decode('utf-8')


def rsa_decrypt(data: str) -> str:
    """
    Decrypt Base64-encoded RSA ciphertext using private key (PKCS#1) with chunking.
    
    Handles both single-chunk and multi-chunk ciphertexts.
    Multi-chunk format is produced when the original message exceeded
    the RSA key's maximum message size.
    
    Args:
        data: Base64-encoded RSA ciphertext from server
        
    Returns:
        Decrypted plaintext JSON string
    """
    encrypted_data = base64.b64decode(data)
    
    try:
        import rsa
        priv_key = rsa.PrivateKey.load_pkcs1(PRIVATE_KEY_PEM.encode(), format='PEM')
        keylength = rsa.common.byte_size(priv_key.n)
        
        decrypted_chunks = []
        for i in range(0, len(encrypted_data), keylength):
            chunk = encrypted_data[i:i + keylength]
            decrypted = rsa.decrypt(chunk, priv_key)
            decrypted_chunks.append(decrypted)
        
        return b''.join(decrypted_chunks).decode('utf-8')
        
    except ImportError:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import padding
        priv_key = serialization.load_pem_private_key(PRIVATE_KEY_PEM.encode(), password=None)
        decrypted = priv_key.decrypt(encrypted_data, padding.PKCS1v15())
        return decrypted.decode('utf-8')


# =============================================================================
# HTTP Request Functions
# =============================================================================

def parse_response(resp_text: str) -> dict:
    """
    Parse server response, attempting RSA decryption if needed.
    
    Server responses come in two forms:
    1. Plain JSON (rare): {"code":"0", "scantronId":"xxx"}
    2. Encrypted Base64 (common): "U9Xx7vK2mP..."
    
    This function tries both approaches.
    
    Args:
        resp_text: Raw response body from server
        
    Returns:
        Parsed dict from decrypted or plain JSON
    """
    if not resp_text:
        return {}
    
    # Try plain JSON first
    try:
        return json.loads(resp_text)
    except json.JSONDecodeError:
        pass
    
    # Try RSA decryption (response is base64-encoded encrypted string)
    try:
        decrypted = rsa_decrypt(resp_text)
        return json.loads(decrypted)
    except Exception:
        # If decryption fails too, return as-is for debugging
        return {"raw_response": resp_text[:200]}


def post_encrypted(endpoint: str, payload: dict, sess: requests.Session) -> dict:
    """
    Send RSA-encrypted POST request to official API.
    
    Request flow:
        dict payload -> JSON string -> RSA encrypt -> Base64 -> HTTP POST
    
    Response flow:
        HTTP body -> Base64 decode -> RSA decrypt -> JSON parse -> dict
    
    Used for APIs: getRunBegin, sunRunExercises, login, getSunRunPaper, etc.
    
    Args:
        endpoint: API path (e.g. 'sunrun/getRunBegin')
        payload: Plaintext dict to send
        sess: requests Session object with headers
        
    Returns:
        Decrypted response dict from server
    """
    encrypted = rsa_encrypt(json.dumps(payload))
    url = f"{BASE_URL}/{endpoint}"
    
    print(f"\n[POST] {url}")
    print(f"[BODY] {json.dumps(payload, ensure_ascii=False)}")
    
    resp = sess.post(url, data=encrypted, verify=False, timeout=15)
    resp.raise_for_status()
    
    result = parse_response(resp.text)
    print(f"[RESP] {json.dumps(result, ensure_ascii=False)[:300]}")
    return result


def post_json(endpoint: str, payload: dict, sess: requests.Session) -> dict:
    """
    Send plaintext JSON POST request to official API.
    
    Unlike post_encrypted(), this sends raw JSON without RSA encryption.
    Used only for: sunRunExercisesDetail (GPS track submission).
    
    Args:
        endpoint: API path (e.g. 'platform/recrecord/sunRunExercisesDetail')
        payload: Plaintext dict to send
        sess: requests Session object with headers
        
    Returns:
        Response dict from server (usually plain JSON for this endpoint)
    """
    url = f"{BASE_URL}/{endpoint}"
    
    print(f"\n[POST] {url}")
    print(f"[BODY] {json.dumps(payload, ensure_ascii=False)[:120]}...")
    
    resp = sess.post(url, json=payload, headers={'Content-Type': 'application/json'},
                     verify=False, timeout=15)
    resp.raise_for_status()
    
    result = parse_response(resp.text)
    print(f"[RESP] {json.dumps(result, ensure_ascii=False)[:300]}")
    return result


# =============================================================================
# Utility Functions
# =============================================================================

def generate_mac(stu_number: str) -> str:
    """
    Generate device MAC address from student number.
    
    Format: XX:XX:XX:XX:XX:XX (6 pairs of hex digits separated by colons)
    Example: "17:b0:2b:f2:81:8c"
    
    Based on totoroschool API documentation, MAC should be in standard
    hardware address format with colons, not a plain hex string.
    
    Args:
        stu_number: Student ID string
        
    Returns:
        Standard MAC address string (17 chars with colons)
    """
    hash_hex = hashlib.sha256(stu_number.encode()).hexdigest()[:12]
    return ':'.join(hash_hex[i:i+2] for i in range(0, 12, 2))


# =============================================================================
# Core Business Logic
# =============================================================================

def submit_run(route_data: dict, token: str, stu_number: str, school_id: str, campus_id: str) -> bool:
    """
    Complete run submission workflow.
    
    Sends 3 API calls in sequence:
    1. getRunBegin: Notify server that run has started
    2. sunRunExercises: Submit run summary (time, distance, speed, steps, MAC)
    3. sunRunExercisesDetail: Submit GPS track coordinates
    
    Args:
        route_data: Dict from route.json containing:
            - mockRoute: List of GPS coordinates
            - startTime, endTime, usedTime: Time info
            - avgSpeed, targetDistance: Performance metrics
            - routeInfo: {taskId, pointId, pointName}
        token: Login token from session.json
        stu_number: Student number
        school_id: School ID
        campus_id: Campus ID
        
    Returns:
        True if all steps succeed, False otherwise
    """
    sess = requests.Session()
    sess.headers.update({
        'User-Agent': 'TotoroSchool/1.2.14 (iPhone; iOS 17.4.1; Scale/3.00)',
        'Content-Type': 'application/json; charset=utf-8',
        'Accept': 'application/json',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive',
        'Host': 'app.xtotoro.com',
    })

    print("=" * 60)
    print("Totoro Run Submission (Official API)")
    print("=" * 60)
    print(f"Route: {route_data['routeInfo']['pointName']}")
    print(f"Distance: {route_data['targetDistance']} km")
    print(f"Time: {route_data['startTime']} ~ {route_data['endTime']}")
    print(f"Duration: {route_data['usedTime']}")
    print(f"Speed: {route_data['avgSpeed']} km/h")
    print(f"Track: {route_data['pointCount']} points")

    # -------------------------------------------------------------------------
    # Step 1: getRunBegin
    # Purpose: Notify server that user has started running.
    # Payload: Basic user info (token, stuNumber, schoolId)
    # Response: Generic success message (no critical data)
    # -------------------------------------------------------------------------
    print("\n--- Step 1: getRunBegin ---")
    try:
        post_encrypted('sunrun/getRunBegin', {
            "campusId": campus_id,
            "schoolId": school_id,
            "stuNumber": stu_number,
            "token": token
        }, sess)
        print("OK")
    except Exception as e:
        print(f"WARN: {e}")

    # -------------------------------------------------------------------------
    # Step 2: sunRunExercises (Summary)
    # Purpose: Submit all run metadata (the "report card").
    # Payload: time, distance, speed, steps, device info, MAC, etc.
    # Response: {scantronId: "xxx"} — needed for Step 3
    # Note: pointList field is empty string here, track goes in Step 3
    # -------------------------------------------------------------------------
    print("\n--- Step 2: sunRunExercises (Summary) ---")
    summary = {
        "LocalSubmitReason": "",
        "avgSpeed": route_data['avgSpeed'],
        "baseStation": "",
        "endTime": route_data['endTime'],
        "evaluateDate": route_data['evaluateDate'],
        "fitDegree": "1",
        "flag": "1",
        "headImage": "",
        "ifLocalSubmit": "1",
        "km": route_data['targetDistance'],
        "mac": generate_mac(stu_number),
        "phoneInfo": "$CN11/iPhone15,4/17.4.1",
        "phoneNumber": "",
        "pointList": "",
        "routeId": route_data['routeInfo']['pointId'],
        "runType": "0",
        "sensorString": "",
        "startTime": route_data['startTime'],
        "steps": route_data['steps'],
        "stuNumber": stu_number,
        "taskId": route_data['routeInfo']['taskId'],
        "token": token,
        "usedTime": route_data['usedTime'],
        "version": "1.2.14",
        "warnFlag": "0",
        "warnType": "",
        "faceData": ""
    }
    result = post_encrypted('platform/recrecord/sunRunExercises', summary, sess)
    scantron_id = result.get('scantronId')
    if not scantron_id:
        print(f"FAIL: no scantronId: {result}")
        return False
    print(f"OK: scantronId={scantron_id}")

    # -------------------------------------------------------------------------
    # Step 3: sunRunExercisesDetail (GPS Track)
    # Purpose: Submit actual GPS coordinates.
    # Payload: pointList (array of {longitude, latitude}), scantronId
    # Note: Sent as PLAIN JSON (not encrypted)
    # Response: Generic success
    # -------------------------------------------------------------------------
    print("\n--- Step 3: sunRunExercisesDetail (Track) ---")
    track = {
        "pointList": route_data['mockRoute'],
        "scantronId": scantron_id,
        "stuNumber": stu_number,
        "token": token
    }
    post_json('platform/recrecord/sunRunExercisesDetail', track, sess)
    print(f"OK: {len(route_data['mockRoute'])} points sent")

    print("\n" + "=" * 60)
    print("DONE")
    print("=" * 60)
    return True


# =============================================================================
# Entry Point
# =============================================================================

def main():
    """
    CLI entry point.
    
    Reads command-line arguments, loads route data and credentials,
    then calls submit_run() to perform the full submission.
    
    Credential priority (highest first):
    1. --token / --stu-number command line args
    2. session.json file (--config)
    """
    parser = argparse.ArgumentParser(
        description='Submit run record to Totoro official API',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Use session.json (default)
    python submit_run.py --route-file route.json

    # Override token
    python submit_run.py --route-file route.json --token "APPx..."

    # Full manual credentials
    python submit_run.py --route-file route.json \\
        --token "APPx..." --stu-number "162320316" --school-id "98765"
        """
    )
    parser.add_argument('--route-file', type=str, default='route.json',
                        help='Route JSON file generated by route.py (default: route.json)')
    parser.add_argument('--config', type=str, default='session.json',
                        help='Credentials file containing session.token, session.stuNumber, etc. (default: session.json)')
    parser.add_argument('--token', type=str, default='',
                        help='Override: Totoro login token')
    parser.add_argument('--stu-number', type=str, default='',
                        help='Override: Student number')
    parser.add_argument('--school-id', type=str, default='',
                        help='Override: School ID')
    parser.add_argument('--campus-id', type=str, default='',
                        help='Override: Campus ID')
    args = parser.parse_args()

    # Check RSA library availability
    try:
        import rsa
    except ImportError:
        try:
            import cryptography
        except ImportError:
            print("[ERR] RSA library not found. Install with: pip install rsa")
            sys.exit(1)

    # Load route data from generated file
    print(f"Loading route: {args.route_file}")
    with open(args.route_file, 'r', encoding='utf-8') as f:
        route_data = json.load(f)

    # Load credentials from config file
    creds = {}
    if Path(args.config).exists():
        with open(args.config, 'r', encoding='utf-8') as f:
            data = json.load(f)
        creds = data.get('session', {})

    # Resolve final credentials (CLI args override config file)
    token = args.token or creds.get('token', '')
    stu_number = args.stu_number or creds.get('stuNumber', '')
    school_id = args.school_id or creds.get('schoolId', '')
    campus_id = args.campus_id or creds.get('campusId', '')

    if not token or not stu_number:
        print("[ERR] Missing token or stuNumber")
        print("Provide via --config session.json or --token/--stu-number")
        sys.exit(1)

    print(f"stuNumber: {stu_number}")
    print(f"schoolId: {school_id}")
    print(f"campusId: {campus_id}")

    ok = submit_run(route_data, token, stu_number, school_id, campus_id)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
